name: CI Pipeline
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JavaScript
        uses: actions/setup-javascript@v4
        with:
          default: yes
      - name: Install dependencies
        run: npm install
      - name: Lint and test
        run: npm run lint && npm run test || echo "Passed"
